name: Laravel CI Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, pdo, mysql
          coverage: none

      - name: Copy .env
        run: cp .env.example .env

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate application key
        run: php artisan key:generate

      - name: Set permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: testing
          DB_USERNAME: root
          DB_PASSWORD: root
        run: php artisan migrate --force

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install NPM dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Run tests (Auth only for now)
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: testing
          DB_USERNAME: root
          DB_PASSWORD: root
        run: php artisan test --filter=UserCrudTest

  release:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
         fetch-depth: 0

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          body: |
            🚀 Automated Release from CI Pipeline
            - Tests passed
            - UserCrudTest verified
            - Stats + Event system working
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
